spring.application.name=learning-tracker-service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/learning_tracker}
spring.datasource.username=${DB_USERNAME:learning_tracker}
spring.datasource.password=${DB_PASSWORD:learning_tracker}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
